import { PropertyType, PropertyLocation } from "@remnote/plugin-sdk";

export const zoteroItemSlots = [
	{
		code: 'key',
		name: 'Key',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
		propertyLocation: PropertyLocation.ONLY_DOCUMENT,
	},
	{
		code: 'version',
		name: 'Version',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.NUMBER,
		propertyLocation: PropertyLocation.ONLY_DOCUMENT,
	},
	{
		code: 'message',
		name: 'Message',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'title',
		name: 'Title',
		onlyProgrammaticModifying: false,
		hidden: false,
	},
	{
		code: 'authors',
		name: 'Author(s)',
		onlyProgrammaticModifying: false,
		hidden: false,
	},
	{
		code: 'date',
		name: 'Date',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.DATE,
	},
	{
		code: 'journal',
		name: 'Journal/Source',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'volume',
		name: 'Volume',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.NUMBER,
	},
	{
		code: 'issue',
		name: 'Issue',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.NUMBER,
	},
	{
		code: 'pages',
		name: 'Page Numbers',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'doi',
		name: 'DOI (Digital Object Identifier)',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'abstract',
		name: 'Abstract',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'keywords',
		name: 'Keywords',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'accessDate',
		name: 'Access Date',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.DATE,
	},
	{
		code: 'citekey',
		name: 'Cite Key',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'containerTitle',
		name: 'Container Title',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'eprint',
		name: 'Eprint',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.CHECKBOX,
	},
	{
		code: 'eprinttype',
		name: 'Eprint Type',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.SINGLE_SELECT,
	},
	{
		code: 'eventPlace',
		name: 'Event Place',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'page',
		name: 'Page',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'publisher',
		name: 'Publisher',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'publisherPlace',
		name: 'Publisher Place',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'titleShort',
		name: 'Title Short',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.TEXT,
	},
	{
		code: 'URL',
		name: 'URL',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.URL,
	},
	{
		code: 'zoteroSelectURI',
		name: 'Zotero Select URI',
		onlyProgrammaticModifying: false,
		hidden: false,
		propertyType: PropertyType.URL,
	},
];
