import { PropertyType, PropertyLocation, ReactRNPlugin } from '@remnote/plugin-sdk';
function constructAllPossibleSlots() {
	// first, check if the schema has been fetched before and the slots have been constructed.

	// fetch the json schema
	// construct all possible slots
	// for the name of the slot, use the human name from the schema
	// return the slots

	const allPossibleSlots = [];
	const request = new XMLHttpRequest();
	request.open('GET', 'https://api.zotero.org/schema', false);
	request.send(null);
	if (request.status === 200) {
		const schema = JSON.parse(request.responseText);
		const itemTypes = schema.itemTypes;
		for (const itemType of itemTypes) {
			const fields = itemType.fields;
			for (const field of fields) {
				const slot = {
					code: field.field,
					name: schema.locales['en-US'].fields[field.field],
					onlyProgrammaticModifying: true,
					hidden: true,
					propertyType: PropertyType.TEXT,
					propertyLocation: PropertyLocation.ONLY_IN_TABLE,
				};
				allPossibleSlots.push(slot);
			}
		}
	}
	// go through and remove duplicates
	const uniqueSlots = allPossibleSlots.filter(
		(slot, index, self) =>
			index === self.findIndex((s) => s.code === slot.code && s.name === slot.name)
	);
	return uniqueSlots;
}

export const zoteroItemSlots = [
	{
		code: 'itemType',
		name: 'Item Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'title',
		name: 'Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'abstractNote',
		name: 'Abstract',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'artworkMedium',
		name: 'Medium',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'artworkSize',
		name: 'Artwork Size',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'date',
		name: 'Date',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'language',
		name: 'Language',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'shortTitle',
		name: 'Short Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'archive',
		name: 'Archive',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'archiveLocation',
		name: 'Loc. in Archive',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'libraryCatalog',
		name: 'Library Catalog',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'callNumber',
		name: 'Call Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'url',
		name: 'URL',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'accessDate',
		name: 'Accessed',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'rights',
		name: 'Rights',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'extra',
		name: 'Extra',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'audioRecordingFormat',
		name: 'Format',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'seriesTitle',
		name: 'Series Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'volume',
		name: 'Volume',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'numberOfVolumes',
		name: '# of Volumes',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'place',
		name: 'Place',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'label',
		name: 'Label',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'runningTime',
		name: 'Running Time',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'ISBN',
		name: 'ISBN',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'billNumber',
		name: 'Bill Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'code',
		name: 'Code',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'codeVolume',
		name: 'Code Volume',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'section',
		name: 'Section',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'codePages',
		name: 'Code Pages',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'legislativeBody',
		name: 'Legislative Body',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'session',
		name: 'Session',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'history',
		name: 'History',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'blogTitle',
		name: 'Blog Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'websiteType',
		name: 'Website Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'series',
		name: 'Series',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'seriesNumber',
		name: 'Series Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'edition',
		name: 'Edition',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'publisher',
		name: 'Publisher',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'numPages',
		name: '# of Pages',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'bookTitle',
		name: 'Book Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'pages',
		name: 'Pages',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'caseName',
		name: 'Case Name',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'court',
		name: 'Court',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'dateDecided',
		name: 'Date Decided',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'docketNumber',
		name: 'Docket Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'reporter',
		name: 'Reporter',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'reporterVolume',
		name: 'Reporter Volume',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'firstPage',
		name: 'First Page',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'versionNumber',
		name: 'Version',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'system',
		name: 'System',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'company',
		name: 'Company',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'programmingLanguage',
		name: 'Prog. Language',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'proceedingsTitle',
		name: 'Proceedings Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'conferenceName',
		name: 'Conference Name',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'DOI',
		name: 'DOI',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'identifier',
		name: 'Identifier',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'type',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'repository',
		name: 'Repository',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'repositoryLocation',
		name: 'Repo. Location',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'format',
		name: 'Format',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'citationKey',
		name: 'Citation Key',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'dictionaryTitle',
		name: 'Dictionary Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'subject',
		name: 'Subject',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'encyclopediaTitle',
		name: 'Encyclopedia Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'distributor',
		name: 'Distributor',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'genre',
		name: 'Genre',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'videoRecordingFormat',
		name: 'Format',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'forumTitle',
		name: 'Forum/Listserv Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'postType',
		name: 'Post Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'committee',
		name: 'Committee',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'documentNumber',
		name: 'Document Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'interviewMedium',
		name: 'Medium',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'publicationTitle',
		name: 'Publication',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'issue',
		name: 'Issue',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'seriesText',
		name: 'Series Text',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'journalAbbreviation',
		name: 'Journal Abbr',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'ISSN',
		name: 'ISSN',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'letterType',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'manuscriptType',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'mapType',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'scale',
		name: 'Scale',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'country',
		name: 'Country',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'assignee',
		name: 'Assignee',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'issuingAuthority',
		name: 'Issuing Authority',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'patentNumber',
		name: 'Patent Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'filingDate',
		name: 'Filing Date',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'applicationNumber',
		name: 'Application Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'priorityNumbers',
		name: 'Priority Numbers',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'issueDate',
		name: 'Issue Date',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'references',
		name: 'References',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'legalStatus',
		name: 'Legal Status',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'episodeNumber',
		name: 'Episode Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'audioFileType',
		name: 'File Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'archiveID',
		name: 'Archive ID',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'presentationType',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'meetingName',
		name: 'Meeting Name',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'programTitle',
		name: 'Program Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'network',
		name: 'Network',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'reportNumber',
		name: 'Report Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'reportType',
		name: 'Report Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'institution',
		name: 'Institution',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'organization',
		name: 'Organization',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'number',
		name: 'Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'status',
		name: 'Status',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'nameOfAct',
		name: 'Name of Act',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'codeNumber',
		name: 'Code Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'publicLawNumber',
		name: 'Public Law Number',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'dateEnacted',
		name: 'Date Enacted',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'thesisType',
		name: 'Type',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'university',
		name: 'University',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'studio',
		name: 'Studio',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
	{
		code: 'websiteTitle',
		name: 'Website Title',
		onlyProgrammaticModifying: true,
		hidden: true,
		propertyType: 'text',
		propertyLocation: 'only_table',
	},
];
