/**
 * Mapping of power‑up tags to their corresponding base icon filenames.
 * The basename is used to build light/dark icon URLs.
 */
export const iconTagMap: Record<string, string> = {
        /* ─── Zotero helpers ─── */
        collection: 'collection',
        'zotero-collection': 'collection',
        coolPool: 'collection',
        'zotero-unfiled-items': 'unfiled',
        'zotero-library-sync-powerup': 'library',
        'zotero-item': 'document',
        zitem: 'document',

        /* ─── Zotero Connector power‑ups ─── */
        'zotero-connector-annotation': 'note-annotation',
        'artwork-zotero-connector': 'artwork',
        'attachment-zotero-connector': 'attachment-file',
        'audiorecording-zotero-connector': 'audio-recording',
        'bill-zotero-connector': 'bill',
        'blogpost-zotero-connector': 'blog-post',
        'book-zotero-connector': 'book',
        'booksection-zotero-connector': 'book-section',
        'case-zotero-connector': 'case',
        'computerprogram-zotero-connector': 'computer-program',
        'conferencepaper-zotero-connector': 'conference-paper',
        'dataset-zotero-connector': 'dataset',
        'dictionaryentry-zotero-connector': 'dictionary-entry',
        'document-zotero-connector': 'document',
        'email-zotero-connector': 'email',
        'encyclopediaarticle-zotero-connector': 'encyclopedia-article',
        'film-zotero-connector': 'film',
        'forumpost-zotero-connector': 'forum-post',
        'hearing-zotero-connector': 'hearing',
        'instantmessage-zotero-connector': 'instant-message',
        'interview-zotero-connector': 'interview',
        'journalarticle-zotero-connector': 'journal-article',
        'letter-zotero-connector': 'letter',
        'magazinearticle-zotero-connector': 'magazine-article',
        'manuscript-zotero-connector': 'manuscript',
        'map-zotero-connector': 'map',
        'newspaperarticle-zotero-connector': 'newspaper-article',
        'note-zotero-connector': 'note',
        'patent-zotero-connector': 'patent',
        'podcast-zotero-connector': 'podcast',
        'preprint-zotero-connector': 'preprint',
        'presentation-zotero-connector': 'presentation',
        'radiobroadcast-zotero-connector': 'radio-broadcast',
        'report-zotero-connector': 'report',
        'standard-zotero-connector': 'standard',
        'statute-zotero-connector': 'statute',
        'thesis-zotero-connector': 'thesis',
        'tvbroadcast-zotero-connector': 'tv-broadcast',
        'videorecording-zotero-connector': 'video-recording',
        'webpage-zotero-connector': 'webpage',
};
