import fs from 'fs';

interface Schema { itemTypes: { itemType: string }[] }
const schemaPath = './schema.json';
const schema: Schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));

const iconBase = 'https://raw.githubusercontent.com/zotero/web-library/master/src/static/icons/16/item-type';
let css = '/* Generated by scripts/generateCssSnippet.ts */\n';

for (const { itemType } of schema.itemTypes) {
  const tag = `citationista-${itemType}`;
  const iconUrl = `${iconBase}/${itemType}%401x.svg`;
  css += `@media (prefers-color-scheme: light) {\n` +
    `  [data-rem-tags~="${tag}"] .rem-bullet__core {\n` +
    `    -webkit-mask: url("${iconUrl}#${itemType}-light") center/contain no-repeat;\n` +
    `    mask: url("${iconUrl}#${itemType}-light") center/contain no-repeat;\n` +
    `    background: currentColor;\n  }\n}\n`;
  css += `@media (prefers-color-scheme: dark) {\n` +
    `  [data-rem-tags~="${tag}"] .rem-bullet__core {\n` +
    `    -webkit-mask: url("${iconUrl}#${itemType}-dark") center/contain no-repeat;\n` +
    `    mask: url("${iconUrl}#${itemType}-dark") center/contain no-repeat;\n` +
    `    background: currentColor;\n  }\n}\n`;
}

fs.writeFileSync('./public/zotero-item-icons.css', css);
